#!/bin/bash

usage() {
cat <<EOF
battery: usage:

  general:
    -h, --help    print this message
    -t            output tmux status bar format

  colors:
    -g <color>    good battery level      default: green or 0;32
    -m <color>    middle battery level    default: yellow or 0;33
    -w <color>    warn battery level      default: red or 0;31
EOF
}

if [[ $1 == '-h' || $1 == '--help' || $1 == '-?' ]]; then
  usage
  exit 0
fi

# For default behavior
setDefaults() {
  output_tmux=0
  good_color="0;32"
  middle_color="0;33"
  warn_color="0;31"
  connected=0

  BATPATH=/sys/class/power_supply/BAT0
  STATUS=$BATPATH/status
  BAT_FULL=$BATPATH/charge_full
  BAT_NOW=$BATPATH/charge_now
}

setDefaults

battery_charge()
{
    maxcap=$(cat $BAT_FULL)
    curcap=$(cat $BAT_NOW)
    if [[ -n "$maxcap" && -n $curcap ]]; then
        CAPACITY=$(( 100 * curcap / maxcap))
        printf "%d" $CAPACITY
    fi
}

if [[ ! $(cat "$STATUS") = "Discharging" ]]; then
  connected=1
fi


run_battery() {
  BATTERY_STATUS="$(battery_charge)"

[[ -z "$BATTERY_STATUS" ]] && exit 1
}

# Apply the correct color to the battery status prompt
apply_colors() {
# Green
if [[ $BATTERY_STATUS -ge 75 ]]; then
  if ((output_tmux)); then
    COLOR="#[fg=$good_color]"
  else
    COLOR=$good_color
  fi

# Yellow
elif [[ $BATTERY_STATUS -ge 25 ]] && [[ $BATTERY_STATUS -lt 75 ]]; then
  if ((output_tmux)); then
    COLOR="#[fg=$middle_color]"
  else
    COLOR=$middle_color
  fi

# Red
elif [[ $BATTERY_STATUS -lt 25 ]]; then
  if ((output_tmux)); then
    COLOR="#[fg=$warn_color]"
  else
    COLOR=$warn_color
  fi
fi
}

print_status() {
# Print the battery status
if ((connected)); then
  GRAPH="⚡"
fi

if ((output_tmux)); then
  printf "%s%s%s%s" "$COLOR" "[$GRAPH$BATTERY_STATUS%]" "#[default]"
else
  printf "\e[0;%sm%s%s\e[m\n"  "$COLOR" "[$GRAPH$BATTERY_STATUS%]"
fi
}

# Read args
while getopts ":g:m:w:tap" opt; do
  case $opt in
    g)
      good_color=$OPTARG
      ;;
    m)
      middle_color=$OPTARG
      ;;
    w)
      warn_color=$OPTARG
      ;;
    t)
      output_tmux=1
      good_color="green"
      middle_color="yellow"
      warn_color="red"
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument"
      exit 1
      ;;
  esac
done


run_battery
apply_colors
print_status
